### ISSUE TITLE
Create logo for sabah rural farmers

### ISSUE THREAD

**Issue by paragasu** [phisoft/sabahruralfarmers-web#1]
- Koperasi Petani Desa Sabah
- Sabah Rural Farmers Cooperative
- Domain sabahruralframers.org

create letter based logo -> SRF

Logo: 
[sabahruralfarmers-logo.zip](https://github.com/phisoft/sabahruralfarmers-web/files/11195991/sabahruralfarmers-logo.zip)

**Comment by rosclaritha** [comment]
ll

**Comment by rosclaritha** [comment]
https://github.com/phisoft/sabahruralfarmers-web/files/11195991/sabahruralfarmers-logo.zip
