### ISSUE TITLE
change font, to ensure all font the same

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/sabahruralfarmers-web#16]
![image](https://user-images.githubusercontent.com/30463117/232368147-9c1ad4e8-d628-4692-a8ad-b5eb756cafb0.png)

**Comment by NadhirahIzzati** [comment]
code for font has been changed alongside other code on another issue.

![Screenshot (588)](https://user-images.githubusercontent.com/74038076/232402803-a05b5f0d-9e79-45d8-a906-8c16c9db691a.png)
![Screenshot (589)](https://user-images.githubusercontent.com/74038076/232402808-ceedde64-ddac-4dec-8484-77b9043e79a7.png)
![Screenshot (590)](https://user-images.githubusercontent.com/74038076/232402826-53be1f43-0fbe-493c-911e-8b24fa4172c8.png)
![Screenshot (591)](https://user-images.githubusercontent.com/74038076/232402830-dd9b54ed-2572-4ccd-86c2-3e613f8fe706.png)
