### ISSUE TITLE
find a suitable bootstrap html theme

### ISSUE THREAD

**Issue by paragasu** [phisoft/sabahruralfarmers-web#2]
Refer this issue: https://github.com/phisoft/roompillow-web/issues/23

Find suitable template for NGO

**Comment by NadhirahIzzati** [comment]
Template 1:
https://www.free-css.com/free-css-templates/page290/brighton

Template 2:
https://www.free-css.com/free-css-templates/page252/nlw-lawn-care

Template 3:
https://www.free-css.com/free-css-templates/page263/above

Template 4:
https://www.free-css.com/free-css-templates/page253/artist

Template 5:
https://www.free-css.com/free-css-templates/page227/exigo

Template 6:
https://www.free-css.com/free-css-templates/page210/worthy-v1.0

Template 7:
https://www.free-css.com/free-css-templates/page205/multi

Template 8:
https://bootstrapmade.com/demo/Impact/

Template 9:
https://bootstrapmade.com/demo/Nova/

Template 10:
https://bootstrapmade.com/demo/Mamba/
