### ISSUE TITLE
suggest image

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/sabahruralfarmers-web#23]
- [ ] suggest a few header image
- [ ] suggest a few about image

![image](https://user-images.githubusercontent.com/30463117/232663955-0412247a-3421-4cfc-8546-fd1cbe2ac482.png)
![image](https://user-images.githubusercontent.com/30463117/232663786-56f8be62-b8b7-4c90-b59e-5527ede71dce.png)

**Comment by NadhirahIzzati** [comment]
about image: 
![pexels-greta-hoffman-7728076](https://user-images.githubusercontent.com/74038076/232704142-7c1d49e3-5393-4dec-bac0-071e7a8ada25.jpg)
![pexels-greta-hoffman-7728077](https://user-images.githubusercontent.com/74038076/232704162-b54b3087-43e8-43ec-af56-45175bbcb28c.jpg)
![pexels-greta-hoffman-7728882](https://user-images.githubusercontent.com/74038076/232704179-64e95c60-f5a2-4ba4-8191-b0fac58b1f18.jpg)
![pexels-max-ravier-2253815](https://user-images.githubusercontent.com/74038076/232704192-ecf7b303-07d1-433b-aa80-bb29fe402b62.jpg)
![pexels-zen-chung-5529591](https://user-images.githubusercontent.com/74038076/232704211-ec907123-11c5-4903-abd0-d8fd018879a6.jpg)
![zoe-schaeffer-PFbOZfKh07I-unsplash](https://user-images.githubusercontent.com/74038076/232704240-b0446154-7a8e-49e2-b4c0-03c111d7fd21.jpg)

**Comment by NadhirahIzzati** [comment]
header image suggestion:
![pexels-greta-hoffman-7728874](https://user-images.githubusercontent.com/74038076/232705537-c4026ae3-e80b-4bc1-9809-dc89946909c3.jpg)
![pexels-quang-nguyen-vinh-2131784](https://user-images.githubusercontent.com/74038076/232705561-38380608-d497-4b6e-8054-4f786807d23e.jpg)
![pexels-tomas-anunziata-3876417](https://user-images.githubusercontent.com/74038076/232705570-7cbe7671-754f-4433-8fcb-0597fa0ed7db.jpg)
![portrait-asian-farmer-man-woman-holding-wooden-box-full-fresh-raw-vegetables-organic-farm-concept](https://user-images.githubusercontent.com/74038076/232705608-db5581e9-fcfc-4390-b365-be0485c8ba30.jpg)
]()
![sandie-clarke-q13Zq1Jufks-unsplash](https://user-images.githubusercontent.com/74038076/232706115-4f0f7f04-d2a9-46db-97c3-6d7a55fc0ea1.jpg)

**Comment by NadhirahIzzati** [comment]
header suggestions as seen on website:
1: 
![Screenshot (607)](https://user-images.githubusercontent.com/74038076/232953365-14ee8ed3-2f34-424d-8867-5a79581e64e9.png)
2: 
![Screenshot (608)](https://user-images.githubusercontent.com/74038076/232953403-9d916ff9-d2f3-4a64-bb68-79aa67b2e529.png)
3. 
![Screenshot (609)](https://user-images.githubusercontent.com/74038076/232953424-de8c186f-a68f-452d-9f61-cf3f02e6ec84.png)
4.  
![Screenshot (611)](https://user-images.githubusercontent.com/74038076/232953516-9b0234ed-2f6e-46ab-9451-a43276a1dcc2.png)
5.
![Screenshot (610)](https://user-images.githubusercontent.com/74038076/232953447-49e83d3a-a85f-4e6a-aab2-9590a4e40b7c.png)

**Comment by NadhirahIzzati** [comment]
about image suggestion on website:
1. 
![Screenshot (601)](https://user-images.githubusercontent.com/74038076/232954112-f955198c-e0d8-4490-ba57-3d1b6eb2d06a.png)
2. 
![Screenshot (602)](https://user-images.githubusercontent.com/74038076/232954134-e587f257-d365-459b-a92d-da6536ae54a6.png)
3. 
![Screenshot (603)](https://user-images.githubusercontent.com/74038076/232954164-47a287c3-d9f3-4942-bb14-1f2824b021e1.png)
4.
![Screenshot (604)](https://user-images.githubusercontent.com/74038076/232954201-9e9702cb-4093-4ed0-9b44-5d5fdd76831e.png)
5.  
![Screenshot (606)](https://user-images.githubusercontent.com/74038076/232954272-8c6ee942-7f31-4aa1-b75d-49d694a92f7d.png)
6.
![Screenshot (605)](https://user-images.githubusercontent.com/74038076/232954254-2f48cf20-4c99-4484-a731-5d53d5bfad12.png)

**Comment by rosclaritha** [comment]
@NadhirahIzzati 
![image](https://user-images.githubusercontent.com/30463117/232956245-eaba783e-6f01-4696-b65d-ac6d9c564e8d.png)

![image](https://user-images.githubusercontent.com/30463117/232956188-c54ade31-7fca-4532-9adb-7221f45b473d.png)
