### ISSUE TITLE
Create one page website mockup

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/sabahruralfarmers-web#3]
Logo: https://github.com/phisoft/sabahruralfarmers-web/files/11195448/sabahruralfarmers-logo.zip%5D

Follow this template: https://bootstrapmade.com/demo/Mamba/

Sample:
![image](https://user-images.githubusercontent.com/30463117/231037245-e4ed48cb-764d-451c-8aad-aba6aa26ade6.png)
![image](https://user-images.githubusercontent.com/30463117/231037325-0ced0962-9633-4c2c-9e81-977714e5fdca.png)

This company is similar to https://kpd.sabah.gov.my/
Content, use https://chat.openai.com/ to get copywriting ideas:
- [x] Header
- [x] Tagline: Empowering Rural Farmers, Harvesting Sustainable Futures
- [x] Project:  Supporting sustainable agriculture in rural communities - location: Kg. Bilangau Besar, Pitas
Our service allows farmers to rent land from us to plant corn and other crops, providing them with a valuable source of income and helping to ensure their livelihoods. By working with us, farmers can access high-quality land at an affordable price, enabling them to grow healthy and nutritious crops that can be sold locally or regionally.

We believe in the importance of supporting small-scale farmers and promoting sustainable agriculture practices. That's why we work closely with our farmers to provide them with the support they need to succeed, including access to training and technical assistance.

At the same time, we are committed to responsible land stewardship, ensuring that our land is managed sustainably and with respect for the environment. We believe that by working together, we can create a more just and equitable food system that benefits farmers, consumers, and the planet.

So whether you're a farmer looking for land to grow your crops or a landowner interested in supporting sustainable agriculture, we invite you to learn more about our services and how we can work together to create a more just and sustainable future.
- the idea is above, please make your own copywriting.

- [x] vision, mission - give suggestions
- [x] provide suitable copywriting and picture

**Comment by NadhirahIzzati** [comment]
/in progress
![Screenshot (566)](https://user-images.githubusercontent.com/74038076/231099534-bf4aaf1e-139b-4a54-9df1-4f1e51234c3a.png)
![Screenshot (567)](https://user-images.githubusercontent.com/74038076/231099560-b494c3a7-e261-44ae-8791-689c67c3e7ec.png)
![Screenshot (565)](https://user-images.githubusercontent.com/74038076/231099567-befa5488-f0c2-403d-b834-7ac85d0140eb.png)

**Comment by NadhirahIzzati** [comment]
https://www.figma.com/file/VvTbk7ZYZOShpCtyaVvuyC/One-Page-Mockup-(sabahruralfarmers)?node-id=0%3A1&t=JhZPX0RANOnmaozl-1
![One Page Mockup (sabahruralfarmers)](https://user-images.githubusercontent.com/74038076/231347563-0ddf1949-4237-4fdc-a412-5863304cba2c.png)

**Comment by rosclaritha** [comment]
@NadhirahIzzati 

theme color: #1e6052
- [x] change the footer, follow theme color.
- [x] the overall too orange, change to following green theme color
- [x] remove team, portfolio
- [ ] change faq design
- [x] the header remove the bottom navigation
- [ ] change font

**Comment by NadhirahIzzati** [comment]
![One Page Mockup (sabahruralfarmers)](https://user-images.githubusercontent.com/74038076/231380314-85b37726-855c-4d5b-afba-85fd531d83d7.png)

- theme color updated accordingly
- faq design changed
- font changed from raleway & open sans to poppins & raleway
- team & portfolio removed

**Comment by rosclaritha** [comment]
@NadhirahIzzati make it more clean, can view something like this: https://www.forestsolutions.asia/

looks a bit messy
<img width="902" alt="image" src="https://user-images.githubusercontent.com/30463117/231640895-6f50605d-e2f0-4c22-9d61-13bad58aad87.png">

change vision & mission display
<img width="903" alt="image" src="https://user-images.githubusercontent.com/30463117/231641125-ea7526e1-4857-40be-b581-d8d545cfdaa4.png">

**Comment by NadhirahIzzati** [comment]
![One Page Mockup (sabahruralfarmers)(1)](https://user-images.githubusercontent.com/74038076/231660217-f1048f4f-92dc-4534-b9de-f545a584c226.png)
